import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import "../styles/realestatev3.css";
const money=new Intl.NumberFormat("lt-LT",{style:"currency",currency:"EUR",minimumFractionDigits:2});
const num=new Intl.NumberFormat("lt-LT",{minimumFractionDigits:0,maximumFractionDigits:2});
export default function RealEstateProjectProfile(){
 const {projectId}=useParams(); const [data,setData]=useState(null);
 useEffect(()=>{fetch("/data/crowdpear.json").then(r=>r.json()).then(setData)},[]);
 const p=useMemo(()=>data?.projects?.find(x=>String(x.id)===String(projectId)),[data,projectId]);
 if(!p)return <div className="re3-state">Kraunami projekto duomenys...</div>;
 const progress=p.invested?Math.min(100,p.repaidPrincipal/p.invested*100):0;
 const risk=Math.round(Math.max(0,Math.min(100,115-p.ltv-({A:0,B:5,C:15,D:28}[p.rating]||15)-(p.delayDays?20:0))));
 return <main className="re3-page"><Link className="re3-back" to="/platforms/crowdpear">← Grįžti į Crowdpear</Link>
 <header className="re3-project-hero"><div className="re3-project-code">{p.code}</div><div><span>REAL ESTATE PROJECT</span><h1>{p.name}</h1><div className="re3-pills"><span>{p.rating} reitingas</span><span>{p.durationMonths} mėn.</span><span className={`status status-${p.status}`}>{p.status==="repaid"?"Užbaigtas":p.status==="delayed"?"Vėluoja":"Aktyvus"}</span></div></div><div><span>Likusi investicija</span><strong>{money.format(p.outstanding)}</strong><small>iš {money.format(p.invested)}</small></div></header>
 <section className="re3-metrics re3-six"><article className="re3-metric"><span>Investuota</span><strong>{money.format(p.invested)}</strong></article><article className="re3-metric"><span>Grąžinta</span><strong>{money.format(p.repaidPrincipal)}</strong></article><article className="re3-metric"><span>Palūkanos</span><strong className="re3-positive">{money.format(p.interestReceived)}</strong></article><article className="re3-metric"><span>Palūkanų norma</span><strong className="re3-positive">{num.format(p.interestRate)} %</strong></article><article className="re3-metric"><span>LTV</span><strong>{num.format(p.ltv)} %</strong></article><article className="re3-metric"><span>Reitingas</span><strong>{p.rating}</strong></article></section>
 <section className="re3-card re3-project-risk"><div><span>PROJECT RISK</span><h2>{risk>=75?"Žema rizika":risk>=55?"Vidutinė rizika":"Padidinta rizika"}</h2><p>Vertinama pagal LTV, reitingą ir vėlavimo būklę.</p></div><b>{risk}<small>/100</small></b><div className="re3-project-facts"><article><span>Paskolos kodas</span><strong>{p.code}</strong></article><article><span>Mokėjimo dažnis</span><strong>{p.paymentFrequency}</strong></article><article><span>Vėlavimas</span><strong>{p.delayDays} d.</strong></article></div></section>
 <section className="re3-two"><section className="re3-card"><div className="re3-card-head"><div><span>PROJECT DETAILS</span><h2>Projekto informacija</h2></div></div><div className="re3-details">{[["Investavimo data",p.investmentDate],["Palūkanų pradžia",p.interestStart||"–"],["Planuojama pabaiga",p.plannedRepayment],["Faktinė pabaiga",p.actualRepayment||"–"],["Terminas",`${p.durationMonths} mėn.`],["Maksimalus LTV",`${num.format(p.maxLtv)} %`]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></section>
 <section className="re3-card"><div className="re3-card-head"><div><span>REPAYMENT PROGRESS</span><h2>Grąžinimo eiga</h2></div></div><div className="re3-repayment"><strong>{num.format(progress)} %</strong><span>grąžinta pagrindinės sumos</span><div><i style={{width:`${progress}%`}}/></div><section><article><span>Grąžinta</span><b>{money.format(p.repaidPrincipal)}</b></article><article><span>Likutis</span><b>{money.format(p.outstanding)}</b></article></section></div></section></section>
 <section className="re3-card"><div className="re3-card-head"><div><span>PAYMENT SCHEDULE</span><h2>Mokėjimų istorija ir grafikas</h2></div></div><div className="re3-table-wrap"><table><thead><tr><th>Planuota data</th><th>Planuota paskola</th><th>Planuotos palūkanos</th><th>Faktinė data</th><th>Grąžinta paskola</th><th>Gautos palūkanos</th><th>Papildomos</th></tr></thead><tbody>{p.payments.map((x,i)=><tr key={i}><td>{x.plannedDate||"–"}</td><td>{money.format(x.plannedPrincipal)}</td><td>{money.format(x.plannedInterest)}</td><td>{x.actualDate||"–"}</td><td>{money.format(x.actualPrincipal)}</td><td className="re3-positive">{money.format(x.actualInterest)}</td><td>{money.format(x.actualExtra)}</td></tr>)}</tbody></table></div></section>
 </main>;
}
